version: '3.8'
services:
    postgres:
        image: postgres:17-alpine
        environment: 
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        ports:
          - "5432:5432"
        networks:
            - postgres-db-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "5050:80"
        volumes:
            - ./servers.json:/pgadmin4/servers.json
        networks:
            - postgres-db-network
        depends_on:
            - postgres
    
    #pgbouncer:
        #environment:
           # DB_HOST: postgres
          #  DB_USER: ${POSTGRES_USER}           # define credentials
          #  DB_PASSWORD: ${POSTGRES_PASSWORD}       # define credentials
          #  DB_port: 5432  
          #  POOL_MODE: transaction    
          #  ADMIN_USER: ${POSTGRES_USER}
       # ports:
         # - "6432:5432"
      #  networks:
           # - postgres-db-network
      #  depends_on:
           # - postgres    # define database
volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: ./data
networks:
    postgres-db-network:
        driver: bridge